apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:
  namespace:
spec:
  rules:
    - host: 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing
                port:
                  number: 
