apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: landing
  namespace: landing
spec:
  rules:
    - host: 
      http:
        paths: landing.apps.ocp4.example.com
          - path: /
            backend:
              serviceName: test
              servicePort: 80
